//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace To_Do_List.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MvcKütüphaneEntities : DbContext
    {
        public MvcKütüphaneEntities()
            : base("name=MvcKütüphaneEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TBLALINTI> TBLALINTI { get; set; }
        public virtual DbSet<TBLKITAPLIK> TBLKITAPLIK { get; set; }
        public virtual DbSet<TBLOKUNACAK> TBLOKUNACAK { get; set; }
        public virtual DbSet<TBLYAZAR> TBLYAZAR { get; set; }
    }
}
