//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace To_Do_List.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLALINTI
    {
        public int AlintiID { get; set; }
        public Nullable<int> KitapAdi { get; set; }
        public string Alinti { get; set; }
    
        public virtual TBLKITAPLIK TBLKITAPLIK { get; set; }
    }
}
