//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace To_Do_List.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLKITAPLIK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLKITAPLIK()
        {
            this.TBLALINTI = new HashSet<TBLALINTI>();
        }
    
        public int KitapID { get; set; }
        public string KitapAdi { get; set; }
        public Nullable<short> KitapYazari { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLALINTI> TBLALINTI { get; set; }
        public virtual TBLYAZAR TBLYAZAR { get; set; }
    }
}
