//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace To_Do_List.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLYAZAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLYAZAR()
        {
            this.TBLKITAPLIK = new HashSet<TBLKITAPLIK>();
        }
    
        public short YazarID { get; set; }
        public string YazarAdi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKITAPLIK> TBLKITAPLIK { get; set; }
    }
}
